package be.tapped.vrtnu.profile

import io.kotest.assertions.arrow.either.shouldBeRight
import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.collections.shouldHaveSize
import io.kotest.matchers.shouldBe

public class JsonFavoriteParserTest : StringSpec({

    "should be able to parse" {
        val favoritesJson = javaClass.classLoader?.getResourceAsStream("favorites.json")!!.reader().readText()
        val favorites = JsonFavoriteParser().parse(favoritesJson)
        favorites.shouldBeRight()
        val favoriteWrapper = favorites.orNull()!!
        favoriteWrapper.size shouldBe 137
        favoriteWrapper.programs shouldBe listOf(
            "vrtnuaz16",
            "vrtnuaz24hoursinpolicecustody",
            "vrtnuaz300millionyears",
            "vrtnuazandthentherewerenone",
            "vrtnuazbancroft",
            "vrtnuazbaptiste",
            "vrtnuazbeforewedie",
            "vrtnuazbiglittlelies",
            "vrtnuazblack",
            "vrtnuazblueplanetiiengelstalig",
            "vrtnuazburen",
            "vrtnuazcampus12",
            "vrtnuazcinemacanvasenemy",
            "vrtnuazcitiesoftomorrow",
            "vrtnuazcivilisations",
            "vrtnuazdagelijksekost",
            "vrtnuazdagelijksezomerkost",
            "vrtnuazdeafspraak",
            "vrtnuazdeafspraakopvrijdag",
            "vrtnuazdecolumbus",
            "vrtnuazdeidealewereld",
            "vrtnuazdemooistesprookjesvangrimm",
            "vrtnuazdenoodcentrale",
            "vrtnuazderidder",
            "vrtnuazdezevendedag",
            "vrtnuazdisconnect",
            "vrtnuazdnanys",
            "vrtnuazdownsideup",
            "vrtnuazdowntheroad",
            "vrtnuazeigenkweek",
            "vrtnuazeltonjohnthenationsfavouritesong",
            "vrtnuazexpeditionvolcano",
            "vrtnuazextratime",
            "vrtnuazextratimekoers",
            "vrtnuazfactcheckers",
            "vrtnuazfcdekampioenen2jubileegeneral",
            "vrtnuazflyingtotheendsoftheearth",
            "vrtnuazfollowthemoney",
            "vrtnuazfortitude",
            "vrtnuazgekengeniaal",
            "vrtnuazgerontophobia",
            "vrtnuazgevoelvoortumor",
            "vrtnuazgoedgezien",
            "vrtnuazgomorra",
            "vrtnuazgraffiti",
            "vrtnuazheldenvandewildernis",
            "vrtnuazhetjournaal",
            "vrtnuazhetlevenzoalshetisautorijschool",
            "vrtnuazhetzomertmet",
            "vrtnuazhistoryuncovered",
            "vrtnuazhootenandthelady",
            "vrtnuazhopenopdegoden",
            "vrtnuaziedereenkiest",
            "vrtnuazinformer",
            "vrtnuazingewikkeld",
            "vrtnuazisereendokterindezaal",
            "vrtnuazjanislittlegirlblue",
            "vrtnuazkaatjeskameraadjes",
            "vrtnuazkies19debestuursniveaus",
            "vrtnuazkies19deinzetvan",
            "vrtnuazkijkuit",
            "vrtnuazkinderenvandecollaboratie",
            "vrtnuazklimaatbetoog",
            "vrtnuazlangzullenwelezen",
            "vrtnuazlazona",
            "vrtnuazlebureaudeslegendes",
            "vrtnuazlesangdelavigne",
            "vrtnuazloslopendwildgevogelte",
            "vrtnuazlouistherouxdarkstatestraffickingsex",
            "vrtnuazlouistherouxtalkingtoanorexia",
            "vrtnuazlouistherouxthenightinquestion",
            "vrtnuazmidsomermurders",
            "vrtnuazmijoverkomthetniet",
            "vrtnuazmvanpeeloverleeft2017",
            "vrtnuaznachtwacht",
            "vrtnuaznachtwacht1",
            "vrtnuazollywannabescomedyclub",
            "vrtnuazonzemaninteheran",
            "vrtnuazopeen",
            "vrtnuazpano",
            "vrtnuazpanorama",
            "vrtnuazprofessort",
            "vrtnuazpubliekgeheim",
            "vrtnuazradio1sessies",
            "vrtnuazrocknrollhighschool",
            "vrtnuazsafehouse",
            "vrtnuazsalamander",
            "vrtnuazsecrets",
            "vrtnuazsportweekend",
            "vrtnuaztaboe",
            "vrtnuaztabularasa",
            "vrtnuaztastesoftheworld",
            "vrtnuazterzake",
            "vrtnuazterzakedocu",
            "vrtnuazterzakeextra",
            "vrtnuazthebridge",
            "vrtnuaztheflame",
            "vrtnuazthehandmaidstale",
            "vrtnuaztheitalianjob",
            "vrtnuazthelawyer",
            "vrtnuazthemissing",
            "vrtnuaztherapie",
            "vrtnuazthestoryofeurope",
            "vrtnuazthrowbackthursday",
            "vrtnuazthuis",
            "vrtnuaztomharry",
            "vrtnuaztomtesterom",
            "vrtnuaztvtouche",
            "vrtnuaztweetotdezesdemacht",
            "vrtnuazundercover",
            "vrtnuazunesoeur",
            "vrtnuazunforgotten",
            "vrtnuazuniversiteitvanvlaanderen",
            "vrtnuazuno",
            "vrtnuazvanalgemeennut",
            "vrtnuazvanatotzdirkdewachter",
            "vrtnuazvanatotzjohanbraeckman",
            "vrtnuazvandaagovereenjaar",
            "vrtnuazvangilsgasten",
            "vrtnuazvdbikbengodniet",
            "vrtnuazvera",
            "vrtnuazversailles",
            "vrtnuazvillapolitica",
            "vrtnuazvillasporza",
            "vrtnuazvivelevelo",
            "vrtnuazwaterfront2018",
            "vrtnuazwegzijnwij",
            "vrtnuazwelkom",
            "vrtnuazwhatseatinggilbertgrape",
            "vrtnuazwherethewildmenare",
            "vrtnuazwinteruur",
            "vrtnuazyibril",
            "vrtnuazyouth",
            "vrtnuazzelfdedeur20jaarlater",
            "vrtnuazziemijgraag",
            "vrtnuazzingaburia",
            "vrtnuazzinzenenvancauwelaertbijivan"
        )

        val favorite = favoriteWrapper["16"]
        favorite shouldBe Favorite(
            1514115647355,
            1514115647355,
            null,
            true,
            "/vrtnu/a-z/16-/",
            "16+",
            "0"
        )

        favoriteWrapper.currentFavorites shouldHaveSize 103
        favoriteWrapper.nonFavorites shouldHaveSize 34
    }
})

